// SOBOLTECH24 — 29 aktywnych ofert Allegro Lokalnie.
// Dane kart: tytuł, kategoria, ceny, opis, parametry i link do ogłoszenia.
const ALLEGRO_BASE = 'https://allegrolokalnie.pl/';
const RAW_PRODUCTS = [
  ["Płyta Samsung NP350E7C LA-8861P + dedykowana grafika Radeon + chłodzenie","Części","180,00 zł","350,00 zł","Sprawna płyta główna Samsung NP350E7C z układem chłodzenia i dedykowaną grafiką Radeon.",[["Platforma","Samsung NP350E7C"],["Oznaczenie płyty","LA-8861P"],["Grafika","dedykowana AMD Radeon"],["Chłodzenie","radiator + wentylator"],["Stan","sprawna"]],"https://allegrolokalnie.pl/oferta/plyta-samsung-np350e7c-la8861p-i73630qm-radeon-sprawna"],
  ["Rower szosowy SCOTT Speedster 40 2016 M/54 Shimano Sora 2x9 | serwis","Akcesoria","1 820,00 zł","1 999,00 zł","Scott Speedster 40 w rozmiarze M/54 z napędem Shimano Sora 2x9, po serwisie.",[["Marka","SCOTT"],["Model","Speedster 40"],["Rok","2016"],["Rama","M / 54 cm"],["Materiał ramy","aluminium 6061"],["Widelec","Speedster Carbon/Alloy"],["Koła","28\" / 700C"],["Napęd","Shimano Sora 2×9 / 18 biegów"],["Korba","Shimano FC-R345 50/34T"],["Opony","700×25C"],["Masa","ok. 9,8 kg"],["Stan","bardzo dobry / po serwisie"]],"https://allegrolokalnie.pl/oferta/rower-szosowy-scott-speedster-40-2016-m54-shimano-sora-2x9-or-serwis"],
  ["Pamięć RAM Samsung 6GB (4GB+2GB) DDR3 1600MHz SO-DIMM PC3-12800S Laptop","RAM","40,00 zł","45,00 zł","Zestaw dwóch modułów pamięci Samsung do laptopa o łącznej pojemności 6 GB.",[["Producent","Samsung"],["Pojemność","6 GB (4 GB + 2 GB)"],["Typ","DDR3"],["Taktowanie","1600 MHz"],["Format","SO-DIMM"],["Klasa","PC3-12800S"]]],
  ["Karta sieciowa Qualcomm/Atheros AR5B225 – Wi‑Fi + Bluetooth","Części","20,00 zł","25,00 zł","Moduł bezprzewodowy Qualcomm/Atheros z obsługą Wi‑Fi oraz Bluetooth.",[["Producent","Qualcomm Atheros"],["Model","AR5B225"],["Funkcje","Wi‑Fi + Bluetooth"],["Interfejs","Half Mini PCIe"],["Pasmo","2,4 GHz"],["Wi‑Fi","802.11 b/g/n"]]],
  ["Dysk HDD Seagate ST500LT012 500GB 2,5” 7mm SATA III + ramka","Dyski","60,00 zł","","Dysk twardy Seagate 500 GB 2,5 cala SATA III o wysokości 7 mm, z ramką montażową.",[["Producent","Seagate"],["Model","ST500LT012"],["Pojemność","500 GB"],["Format","2,5\""],["Interfejs","SATA III"],["Wysokość","7 mm"],["W zestawie","ramka montażowa"]]],
  ["Oryginalna bateria Toshiba PA3536U-1BRS PABAS100 10.8V","Części","50,00 zł","55,00 zł","Oryginalna bateria Toshiba do kompatybilnych laptopów.",[["Producent","Toshiba"],["Model","PA3536U-1BRS"],["Oznaczenie","PABAS100"],["Napięcie","10.8 V"],["Pojemność","4000 mAh"],["Typ","litowo-jonowa"],["Oryginalna","tak"]]],
  ["Oryginalna bateria ASUS A32-K55 10.8V 4400mAh 47Wh","Części","70,00 zł","80,00 zł","Oryginalny akumulator ASUS A32-K55.",[["Producent","ASUS"],["Model","A32-K55"],["Napięcie","10.8 V"],["Pojemność","4400 mAh"],["Energia","47 Wh"],["Typ","litowo-jonowa"],["Oryginalna","tak"]]],
  ["Głośnik konferencyjny EMEET OfficeCore M0 Plus Bluetooth USB – jak nowy","Akcesoria","150,00 zł","200,00 zł","Głośnik konferencyjny EMEET do rozmów online i spotkań, z łącznością Bluetooth i USB.",[["Producent","EMEET"],["Model","OfficeCore M0 Plus"],["Typ","głośnik konferencyjny / speakerphone"],["Łączność","Bluetooth + USB"],["Stan","jak nowy"]],"https://allegrolokalnie.pl/oferta/glosnik-konferencyjny-emeet-officecore-m0-plus-bluetooth-usb-jak-nowy"],
  ["Moduł Bluetooth Toshiba PA3608U-1BTM Taiyo Yuden EYTFXCS z przewodem","Części","12,00 zł","","Moduł Bluetooth Toshiba / Taiyo Yuden wraz z przewodem.",[["Producent","Toshiba / Taiyo Yuden"],["Model","PA3608U-1BTM"],["Oznaczenie modułu","EYTFXCS"],["Typ","moduł Bluetooth"],["W zestawie","moduł + przewód"]]],
  ["Modem telefoniczny Agere Delphi D40 4005B-DELPI Toshiba PK010000000","Części","15,00 zł","","Moduł modemu telefonicznego do starszych laptopów Toshiba.",[["Producent","Agere / Delphi"],["Model","D40 4005B-DELPI"],["Toshiba P/N","PK010000000"],["Typ","modem telefoniczny / laptopowy"]]],
  ["Matryca Samsung LTN170X2-L02 17” 1440x900 CCFL LVDS 30-pin błyszcząca","Części","90,00 zł","120,00 zł","Matryca Samsung 17 cali, 1440×900, CCFL, LVDS 30-pin.",[["Producent","Samsung"],["Model","LTN170X2-L02"],["Przekątna","17\""],["Rozdzielczość","1440 × 900"],["Podświetlenie","CCFL"],["Złącze","LVDS 30-pin"],["Powłoka","błyszcząca"],["Dotyk","nie"]],"https://allegrolokalnie.pl/oferta/matryca-samsung-ltn170x2l02-17-1440x900-ccfl-lvds-30pin-blyszczaca"],
  ["Karta WiFi Bluetooth Ralink RT3290LE HP 690020-001 mini PCI-E","Części","29,99 zł","","Karta WLAN/Bluetooth Ralink do laptopów HP.",[["Producent","Ralink"],["Model","RT3290LE"],["HP P/N","690020-001"],["Interfejs","mini PCI-E"],["Wi‑Fi","802.11n, 2,4 GHz, do 150 Mb/s"],["Bluetooth","tak"]],"https://allegrolokalnie.pl/oferta/karta-wifi-bluetooth-ralink-rt3290le-hp-690020001-mini-pcie"],
  ["Karta WiFi Atheros AR5BXB63 Toshiba WLL3141-D4 mini PCI-E 54 Mb/s","Części","12,00 zł","","Karta Wi‑Fi Atheros / Toshiba mini PCI-E do starszych laptopów.",[["Producent","Toshiba / Atheros"],["Chip","AR5BXB63"],["Model","WLL3141-D4"],["Interfejs","mini PCI-E"],["Prędkość","54 Mb/s"],["Pasmo","2,4 GHz"],["Standard","802.11 b/g"]],"https://allegrolokalnie.pl/oferta/karta-wifi-atheros-ar5bxb63-toshiba-wll3141d4-mini-pcie-54-mbs"],
  ["Touchpad Synaptics TM-00270-000 39T7209 Lenovo IBM ThinkPad T60 T60p","Części","30,00 zł","40,00 zł","Oryginalny touchpad Synaptics do Lenovo/IBM ThinkPad T60 i T60p.",[["Producent","Synaptics"],["Model","TM-00270-000"],["Lenovo/IBM P/N","39T7209"],["Kompatybilność","ThinkPad T60 / T60p"],["Typ","touchpad"]],"https://allegrolokalnie.pl/oferta/touchpad-synaptics-tm00270000-39t7209-lenovo-ibm-thinkpad-t60-t60p"],
  ["Procesor Intel Core i3-2370M 2,40 GHz","Części","20,00 zł","","Mobilny procesor Intel Core i3 drugiej generacji.",[["Model","Intel Core i3-2370M"],["Rdzenie / wątki","2 / 4"],["Taktowanie","2.40 GHz"],["Cache","3 MB"],["TDP","35 W"],["Gniazdo","rPGA988B / Socket G2"],["Grafika","Intel HD Graphics 3000"]]],
  ["Pamięć RAM Micron 4GB DDR3L 1600 MHz PC3L-12800S SO-DIMM","RAM","30,00 zł","","Moduł pamięci Micron DDR3L do laptopa.",[["Producent","Micron"],["Pojemność","4 GB"],["Typ","DDR3L"],["Taktowanie","1600 MHz"],["Format","SO-DIMM"],["Klasa","PC3L-12800S"],["Napięcie","1.35 V"]]],
  ["Pamięć RAM Samsung 2x1GB DDR2 667 MHz SO-DIMM","RAM","20,00 zł","","Komplet dwóch modułów Samsung DDR2 do starszych laptopów.",[["Producent","Samsung"],["Pojemność","2 GB (2 × 1 GB)"],["Typ","DDR2"],["Taktowanie","667 MHz"],["Format","SO-DIMM"],["Klasa","PC2-5300"]]],
  ["Procesor Intel Core 2 Duo T7300 2,00 GHz","Części","32,00 zł","","Dwurdzeniowy procesor mobilny Intel Core 2 Duo.",[["Model","Intel Core 2 Duo T7300"],["Rdzenie / wątki","2 / 2"],["Taktowanie","2.00 GHz"],["Cache L2","4 MB"],["FSB","800 MT/s"],["TDP","35 W"],["Gniazdo","Socket P"]]],
  ["Procesor Intel Pentium Dual-Core T2130 1,86 GHz","Części","25,00 zł","","Procesor Intel Pentium Dual-Core do starszych platform mobilnych.",[["Model","Intel Pentium Dual-Core T2130"],["Rdzenie / wątki","2 / 2"],["Taktowanie","1.86 GHz"],["Cache L2","1 MB"],["FSB","533 MHz"],["TDP","31 W"],["Gniazdo","Socket M"]]],
  ["Matryca 14,1” LG Philips LP141WP1-TLB8 1440x900 WXGA+ 30-pin","Części","80,00 zł","","Matryca LG Philips 14,1 cala o rozdzielczości 1440×900.",[["Producent","LG Philips"],["Model","LP141WP1-TLB8"],["Przekątna","14,1\""],["Rozdzielczość","1440 × 900"],["Klasa","WXGA+"],["Złącze","30-pin"]]],
  ["Matryca LG LP173WD1-TLG1 17,3” 1600x900 HD+ LED 40-pin LVDS","Części","70,00 zł","","Matryca LG 17,3 cala HD+ z podświetleniem LED i złączem LVDS 40-pin.",[["Producent","LG"],["Model","LP173WD1-TLG1"],["Przekątna","17,3\""],["Rozdzielczość","1600 × 900"],["Podświetlenie","LED"],["Złącze","LVDS 40-pin"],["Powłoka","błyszcząca"],["Dotyk","nie"]]],
  ["Szelki bezpieczeństwa PROTEKT P-12 mX PRO XXL + lonża Y AW137 2x AZ023","Akcesoria","200,00 zł","380,00 zł","Szelki bezpieczeństwa PROTEKT z lonżą typu Y i dwoma zatrzaśnikami AZ023.",[["Marka","PROTEKT"],["Model","P-12 mX PRO"],["Rozmiar","XXL"],["Typ","szelki bezpieczeństwa"],["Lonża","Y AW137"],["Zatrzaśniki","2 × AZ023"]]],
  ["Karta Wi‑Fi Ralink RT5390 150 Mb/s Mini PCIe ASUS","Części","15,00 zł","","Karta Wi‑Fi Ralink RT5390 w formacie Mini PCIe.",[["Producent","Ralink"],["Model","RT5390"],["Interfejs","Mini PCIe"],["Pasmo","2,4 GHz"],["Wi‑Fi","802.11n"],["Maks. prędkość","150 Mb/s"]],"https://allegrolokalnie.pl/oferta/karta-wifi-ralink-rt5390-150-mbs-mini-pcie-asus"],
  ["Karta sieciowa Wi‑Fi 5 + Bluetooth 5.0 Realtek RTL8822CE HP M.2","Części","55,00 zł","","Dwupasmowa karta sieciowa Realtek z Wi‑Fi 5 i Bluetooth 5.0.",[["Producent","Realtek"],["Model","RTL8822CE"],["Interfejs","M.2"],["Wi‑Fi","802.11ac / Wi‑Fi 5"],["Maks. prędkość","867 Mb/s"],["Bluetooth","5.0"],["Konfiguracja","2×2 MIMO"]]],
  ["Karta Wi‑Fi Intel 300 Mb/s 2,4/5 GHz Lenovo","Części","30,00 zł","","Dwupasmowa karta Wi‑Fi Intel do laptopa Lenovo.",[["Producent","Intel"],["Maks. prędkość","300 Mb/s"],["Pasma","2,4 / 5 GHz"],["Typ","karta Wi‑Fi do laptopa Lenovo"]]],
  ["Pamięć RAM Hynix 2 GB DDR2 667 MHz PC2-5300S SO-DIMM","RAM","25,00 zł","","Moduł pamięci Hynix DDR2 do starszego laptopa.",[["Producent","Hynix"],["Pojemność","2 GB"],["Typ","DDR2"],["Taktowanie","667 MHz"],["Format","SO-DIMM"],["Klasa","PC2-5300S"]]],
  ["Pamięć RAM Samsung 8 GB 2x4 GB DDR4 3200 MHz","RAM","80,00 zł","","Komplet dwóch modułów Samsung DDR4 o łącznej pojemności 8 GB.",[["Producent","Samsung"],["Pojemność","8 GB (2 × 4 GB)"],["Typ","DDR4"],["Taktowanie","3200 MHz"],["Format","SO-DIMM"]]],
  ["Dysk SSD Western Digital PC SN520 NVMe 128 GB","Dyski","80,00 zł","","Dysk SSD Western Digital PC SN520 NVMe o pojemności 128 GB.",[["Producent","Western Digital"],["Model","PC SN520"],["Pojemność","128 GB"],["Interfejs","NVMe / PCIe"],["Format","M.2"]]],
  ["Ledger Nano S Plus","Akcesoria","220,00 zł","","Sprzętowy portfel Ledger Nano S Plus. Po zakupie urządzenie należy zresetować i samodzielnie wygenerować nową frazę odzyskiwania — nigdy nie używać seed phrase przekazanej przez inną osobę.",[["Producent","Ledger"],["Model","Nano S Plus"],["Typ","sprzętowy portfel kryptowalut"],["Interfejs","USB-C"],["Łączność bezprzewodowa","brak"],["Bateria","brak"],["Zabezpieczenie","Secure Element"]]]
];

const PRODUCTS = RAW_PRODUCTS.map((row,index)=>{
  const [title,category,currentPrice,oldPrice,description,specs,directUrl=''] = row;
  const image = `images/allegro/${String(index+1).padStart(2,'0')}.svg`;
  return {
    title, category, platform:'Allegro Lokalnie', status:'available', currentPrice, oldPrice,
    image, gallery:[image], description,
    specs: specs.map(([label,value])=>({label,value})),
    url: directUrl || `${ALLEGRO_BASE}oferty/q/${encodeURIComponent(title)}`,
    linkType: directUrl ? 'direct' : 'search'
  };
});
